[package]
name = "sketchify"
version = "0.1.0"
authors = ["Søren Mortensen <soren@neros.dev>"]
edition = "2018"
publish = false

[dependencies]
eyre = "^0.6"
reqwest = "^0.9"
tokio = { version = "0.2", features = ["macros"] }
url = "^2.1"

[dependencies.serenity]
version = "0.9.0-rc.1"
default-features = false
features = ["client", "gateway", "rustls_backend", "model"]
